import type { ProjectGraph, Framework } from '../types/index.js';
import type { GeneratorContext } from './base.js';

export interface AiContextOptions {
  claude: boolean;
  cursor: boolean;
  copilot: boolean;
}

export function generateClaudeMd(ctx: GeneratorContext, framework: Framework): string {
  const { graph } = ctx;

  let output = `# Codebase Context (auto-generated by fondamenta)\n\n`;
  output += `> Generated: ${ctx.generatedAt} | Framework: ${framework}\n\n`;

  output += `## Project Structure\n\n`;
  output += `- **Pages:** ${graph.pages.length}\n`;
  output += `- **Components:** ${graph.components.length}\n`;
  output += `- **API Routes:** ${graph.apiRoutes.length}\n`;
  output += `- **Lib Files:** ${graph.libs.length}\n`;
  output += `- **DB Models:** ${graph.schema.models.length}\n`;
  output += `- **Enums:** ${graph.schema.enums.length}\n\n`;

  output += `## Detailed Documentation\n\n`;
  output += `Full atomic analysis available in \`.planning/dependencies/\`:\n`;
  output += `- \`pages-atomic.md\` — every page with imports, auth, data fetching\n`;
  output += `- \`components-atomic.md\` — every component with state, hooks, used-by\n`;
  output += `- \`api-routes-atomic.md\` — every API route with methods, auth, models\n`;
  output += `- \`lib-atomic.md\` — every utility with exports, env vars\n`;
  output += `- \`schema-crossref-atomic.md\` — all DB models, fields, relations\n`;
  output += `- \`component-graph.md\` — visual dependency tree\n`;
  output += `- \`DEPENDENCY-MAP.md\` — impact areas and test checklists\n\n`;

  // Key routes
  output += `## Key Routes\n\n`;
  const topPages = graph.pages.slice(0, 20);
  for (const page of topPages) {
    output += `- \`${page.routePath}\` → \`${page.filePath}\` (${page.componentType}${page.auth !== 'None' ? `, auth: ${page.auth}` : ''})\n`;
  }
  if (graph.pages.length > 20) {
    output += `- ... and ${graph.pages.length - 20} more (see pages-atomic.md)\n`;
  }
  output += '\n';

  // Key models
  if (graph.schema.models.length > 0) {
    output += `## DB Models\n\n`;
    const topModels = graph.schema.models.slice(0, 15);
    for (const model of topModels) {
      const fields = model.fields.slice(0, 5).map((f) => f.name).join(', ');
      const relCount = model.relations.length;
      output += `- \`${model.name}\` — fields: ${fields}${model.fields.length > 5 ? ', ...' : ''}${relCount > 0 ? ` | ${relCount} relations` : ''}\n`;
    }
    if (graph.schema.models.length > 15) {
      output += `- ... and ${graph.schema.models.length - 15} more (see schema-crossref-atomic.md)\n`;
    }
    output += '\n';
  }

  // Fragile zones
  output += `## Fragile Zones\n\n`;
  output += `When modifying these areas, test ALL connected flows:\n\n`;

  const authRoutes = graph.apiRoutes.filter((r) => r.auth !== 'None').length;
  if (authRoutes > 0) {
    output += `- **Auth** — ${authRoutes} protected routes. Changes affect all authenticated pages.\n`;
  }

  const layoutComps = graph.components.filter(
    (c) => c.name.toLowerCase().includes('layout') || c.name.toLowerCase().includes('sidebar'),
  );
  if (layoutComps.length > 0) {
    output += `- **Layout** — ${layoutComps.map((c) => c.name).join(', ')}. Changes affect all pages.\n`;
  }

  // Most-used models
  const modelUsage: Record<string, number> = {};
  for (const route of graph.apiRoutes) {
    for (const model of route.models) {
      modelUsage[model] = (modelUsage[model] || 0) + 1;
    }
  }
  const heavyModels = Object.entries(modelUsage)
    .filter(([, count]) => count >= 3)
    .sort((a, b) => b[1] - a[1]);
  if (heavyModels.length > 0) {
    output += `- **Heavy DB models** — ${heavyModels.map(([m, c]) => `${m} (${c} routes)`).join(', ')}. Schema changes have wide impact.\n`;
  }

  output += '\n';
  return output;
}

export function generateCursorRules(ctx: GeneratorContext, framework: Framework): string {
  const { graph } = ctx;

  let output = `# Codebase rules (auto-generated by fondamenta)\n\n`;
  output += `Framework: ${framework}\n`;
  output += `Pages: ${graph.pages.length} | Components: ${graph.components.length} | API Routes: ${graph.apiRoutes.length} | Models: ${graph.schema.models.length}\n\n`;

  output += `## Architecture\n\n`;
  output += `Full documentation in .planning/dependencies/*.md\n\n`;

  output += `## Conventions\n\n`;

  // Detect patterns
  const clientComponents = graph.components.filter((c) => c.componentType === 'client').length;
  const serverComponents = graph.components.filter((c) => c.componentType === 'server').length;
  output += `- Component split: ${serverComponents} server / ${clientComponents} client\n`;

  const authMethods = new Set(graph.apiRoutes.map((r) => r.auth).filter((a) => a !== 'None'));
  if (authMethods.size > 0) {
    output += `- Auth patterns: ${[...authMethods].join(', ')}\n`;
  }

  // i18n detection
  const i18nPages = graph.pages.filter((p) => p.i18nNamespace).length;
  if (i18nPages > 0) {
    output += `- i18n: ${i18nPages} pages use translations\n`;
  }

  output += '\n';

  // Key files
  output += `## Key Files\n\n`;
  for (const page of graph.pages.slice(0, 10)) {
    output += `- ${page.routePath} → ${page.filePath}\n`;
  }

  output += '\n';
  return output;
}

export function generateCopilotInstructions(ctx: GeneratorContext, framework: Framework): string {
  const { graph } = ctx;

  let output = `# Copilot Instructions (auto-generated by fondamenta)\n\n`;
  output += `This is a ${framework} project with ${graph.pages.length} pages, ${graph.components.length} components, and ${graph.apiRoutes.length} API routes.\n\n`;
  output += `Detailed architecture documentation is available in \`.planning/dependencies/\`.\n\n`;

  output += `## Project Map\n\n`;
  output += `| Area | Count | Documentation |\n`;
  output += `| --- | --- | --- |\n`;
  output += `| Pages | ${graph.pages.length} | .planning/dependencies/pages-atomic.md |\n`;
  output += `| Components | ${graph.components.length} | .planning/dependencies/components-atomic.md |\n`;
  output += `| API Routes | ${graph.apiRoutes.length} | .planning/dependencies/api-routes-atomic.md |\n`;
  output += `| Libraries | ${graph.libs.length} | .planning/dependencies/lib-atomic.md |\n`;
  output += `| DB Models | ${graph.schema.models.length} | .planning/dependencies/schema-crossref-atomic.md |\n\n`;

  if (graph.schema.models.length > 0) {
    output += `## Database Models\n\n`;
    for (const model of graph.schema.models.slice(0, 10)) {
      output += `- \`${model.name}\`: ${model.fields.map((f) => f.name).join(', ')}\n`;
    }
    output += '\n';
  }

  return output;
}
