import chalk from 'chalk';
import type { AgentResult, AgentsRunSummary, AgentFinding } from './types.js';
import type { Agent } from './types.js';

// --- Console output ---

export function printAgentResult(result: AgentResult, agents: Agent[]): void {
  const agent = agents.find((a) => a.id === result.agentId);
  const name = agent?.name ?? result.agentId;

  if (result.skipped) {
    const reason = result.skipReason ?? 'PRO';
    console.log(chalk.dim(`  ○ ${result.agentId} ${dots(result.agentId)} skipped (${reason})`));
    return;
  }

  const count = result.findings.length;
  const errors = result.findings.filter((f) => f.severity === 'error').length;
  const warnings = result.findings.filter((f) => f.severity === 'warning').length;
  const infos = result.findings.filter((f) => f.severity === 'info').length;

  const parts: string[] = [];
  if (errors > 0) parts.push(`${errors} error${errors > 1 ? 's' : ''}`);
  if (warnings > 0) parts.push(`${warnings} warning${warnings > 1 ? 's' : ''}`);
  if (infos > 0) parts.push(`${infos} info`);

  const detail = count === 0
    ? chalk.green('0 findings')
    : parts.join(', ');

  const icon = errors > 0 ? chalk.red('✗') : chalk.green('✓');
  console.log(`  ${icon} ${result.agentId} ${dots(result.agentId)} ${count} findings (${detail})`);
}

export function printFindings(findings: AgentFinding[]): void {
  if (findings.length === 0) return;

  console.log('');

  for (const f of findings) {
    const tag = severityTag(f.severity);
    console.log(`  ${tag}  [${f.agentId}] ${f.title}`);
    if (f.filePath) {
      console.log(chalk.dim(`  │ File: ${f.filePath}`));
    }
    console.log(chalk.dim(`  │ ${f.message}`));
    if (f.suggestion) {
      console.log(chalk.dim(`  │ → ${f.suggestion}`));
    }
    console.log('');
  }
}

export function printSummary(summary: AgentsRunSummary): void {
  const parts: string[] = [];
  if (summary.errors > 0) parts.push(chalk.red(`${summary.errors} error${summary.errors > 1 ? 's' : ''}`));
  if (summary.warnings > 0) parts.push(chalk.yellow(`${summary.warnings} warning${summary.warnings > 1 ? 's' : ''}`));
  if (summary.infos > 0) parts.push(chalk.blue(`${summary.infos} info`));

  const findingStr = parts.length > 0 ? parts.join(', ') : chalk.green('0 issues');
  console.log(`  ${summary.totalFindings} findings: ${findingStr} | ${summary.agentsRan} agents ran | ${summary.totalDurationMs}ms`);
}

// --- Markdown report ---

export function generateAgentsReport(summary: AgentsRunSummary, agents: Agent[]): string {
  const lines: string[] = [];
  const date = new Date().toISOString().split('T')[0];

  lines.push('# Agents Report');
  lines.push('');
  lines.push(`> Generated by Fondamenta ArchCode on ${date}`);
  lines.push('');

  // Summary table
  lines.push('## Summary');
  lines.push('');
  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Total findings | ${summary.totalFindings} |`);
  lines.push(`| Errors | ${summary.errors} |`);
  lines.push(`| Warnings | ${summary.warnings} |`);
  lines.push(`| Info | ${summary.infos} |`);
  lines.push(`| Agents ran | ${summary.agentsRan} |`);
  lines.push(`| Agents skipped | ${summary.agentsSkipped} |`);
  lines.push(`| Duration | ${summary.totalDurationMs}ms |`);
  lines.push('');

  // Per-agent results
  lines.push('## Agent Results');
  lines.push('');

  for (const result of summary.results) {
    const agent = agents.find((a) => a.id === result.agentId);
    const name = agent?.name ?? result.agentId;
    const tier = agent?.tier ?? 'free';

    if (result.skipped) {
      lines.push(`### ${name} \`${tier}\` — Skipped`);
      lines.push('');
      lines.push(`> ${result.skipReason ?? 'PRO license required'}`);
      lines.push('');
      continue;
    }

    const count = result.findings.length;
    lines.push(`### ${name} \`${tier}\` — ${count} finding${count !== 1 ? 's' : ''} (${result.durationMs}ms)`);
    lines.push('');

    if (count === 0) {
      lines.push('No issues found.');
      lines.push('');
      continue;
    }

    for (const f of result.findings) {
      const icon = f.severity === 'error' ? '🔴' : f.severity === 'warning' ? '🟡' : '🔵';
      lines.push(`${icon} **${f.title}**`);
      if (f.filePath) {
        lines.push(`- File: \`${f.filePath}\``);
      }
      lines.push(`- ${f.message}`);
      if (f.suggestion) {
        lines.push(`- Suggestion: ${f.suggestion}`);
      }
      lines.push('');
    }
  }

  return lines.join('\n');
}

// --- Helpers ---

function dots(id: string): string {
  const maxLen = 30;
  const remaining = Math.max(2, maxLen - id.length);
  return chalk.dim('.'.repeat(remaining));
}

function severityTag(severity: AgentFinding['severity']): string {
  switch (severity) {
    case 'error':
      return chalk.bgRed.white(' ERROR ');
    case 'warning':
      return chalk.bgYellow.black(' WARN  ');
    case 'info':
      return chalk.bgBlue.white(' INFO  ');
  }
}
